import { isTradeV2InboxAction, isTradeV2InboxStatus, isTradeV2SubmittedTransition, type ProposalAsset, type TradeV2SubmittedTransition } from './protocol.js'
import type { TradeV2ApiAuth, TradeV2CandidateSubmission, TradeV2CommandAuth, TradeV2ConstructionContext, TradeV2InboxRow, TradeV2TradeRecord } from './contracts.js'
import { TradeV2ApiError, TRADE_V2_USER_SAFE_ERRORS } from './errors.js'
import { discoverTradeV2Capabilities } from './protocol.js'
export type TradeV2TransportRequest = { readonly path: string; readonly method: 'GET' | 'POST'; readonly auth: TradeV2ApiAuth; readonly body?: unknown; readonly idempotencyKey?: string }
export type TradeV2Transport = { request(request: TradeV2TransportRequest): Promise<unknown> }
export type TradeV2FetchTransportOptions = { readonly baseUrl: string; readonly getParticipantAuthHeaders?: (auth: TradeV2ApiAuth, mutating: boolean) => Promise<Record<string, string>>; readonly fetch?: typeof globalThis.fetch }
export function createTradeV2FetchTransport(options: TradeV2FetchTransportOptions): TradeV2Transport {
  const fetcher = options.fetch ?? globalThis.fetch; if (!fetcher) throw new Error('A Fetch implementation is required')
  return { async request(request) {
    const mutating = request.method === 'POST'; if (mutating && !request.idempotencyKey) throw new Error('Mutating Trade V2 requests require an idempotency key')
    const headers: Record<string, string> = { accept: 'application/json', authorization: `Bearer ${request.auth.integrationToken}`, ...(options.getParticipantAuthHeaders ? await options.getParticipantAuthHeaders(request.auth, mutating) : {}) }
    if (request.body !== undefined) headers['content-type'] = 'application/json'; if (request.idempotencyKey) headers['Idempotency-Key'] = request.idempotencyKey
    const response = await fetcher(new URL(request.path, options.baseUrl), { method: request.method, headers, body: request.body === undefined ? undefined : JSON.stringify(request.body) })
    if (!response.ok) { let code = 'HTTP_' + response.status; let diagnosticId: string | null = null; try { const payload = await response.json() as Record<string, unknown>; const envelope = payload.error; if (typeof envelope === 'string') code = envelope; if (envelope && typeof envelope === 'object') { const details = envelope as Record<string, unknown>; if (typeof details.code === 'string') code = details.code; if (typeof details.diagnosticId === 'string') diagnosticId = details.diagnosticId } } catch {} throw new TradeV2ApiError(code, response.status, TRADE_V2_USER_SAFE_ERRORS[code] ?? 'The trade could not be updated safely.', response.status >= 500 || response.status === 429, diagnosticId) }
    return response.json()
  } }
}
export function parseTradeV2InboxRow(raw: unknown): TradeV2InboxRow {
  if (!raw || typeof raw !== 'object') throw new Error('Invalid Trade V2 inbox row'); const value = raw as Record<string, unknown>
  if (!isTradeV2InboxStatus(value.status) || !isTradeV2InboxStatus(value.authoritativeStatus ?? value.status) || !isTradeV2InboxAction(value.action)) throw new Error('Invalid Trade V2 inbox authority fields')
  const actions = value.actions === undefined ? value.action === 'none' ? [] : [value.action] : Array.isArray(value.actions) && value.actions.every(isTradeV2InboxAction) ? value.actions : null; if (!actions) throw new Error('Invalid Trade V2 inbox actions')
  const pending = value.pendingSubmission; if (pending !== null && pending !== undefined && (!pending || typeof pending !== 'object' || !isTradeV2SubmittedTransition((pending as Record<string, unknown>).expectedTransition))) throw new Error('Invalid Trade V2 pending submission')
  const participants = value.participants; if (!participants || typeof participants !== 'object' || typeof (participants as Record<string, unknown>).maker !== 'string' || typeof (participants as Record<string, unknown>).taker !== 'string') throw new Error('Invalid Trade V2 inbox participants')
  const proposal = value.proposal; if (proposal !== null && proposal !== undefined && (!proposal || typeof proposal !== 'object' || !Array.isArray((proposal as Record<string, unknown>).assets) || typeof (proposal as Record<string, unknown>).expiresAt !== 'string' || typeof (proposal as Record<string, unknown>).tradeCommitment !== 'string')) throw new Error('Invalid Trade V2 inbox proposal')
  return { key: String(value.key), tradeId: typeof value.tradeId === 'string' ? value.tradeId : null, proposalId: typeof value.proposalId === 'string' ? value.proposalId : null, escrowPda: typeof value.escrowPda === 'string' ? value.escrowPda : null, direction: value.direction === 'by_me' ? 'by_me' : 'to_me', status: value.status, authoritativeStatus: (value.authoritativeStatus ?? value.status) as TradeV2InboxRow['authoritativeStatus'], action: value.action, actions: actions as TradeV2InboxRow['actions'], active: value.active === true, history: value.history === true, unread: value.unread === true, authority: value.authority === 'oracle' ? 'oracle' : 'off_chain', standardRailSupported: value.standardRailSupported === true, pendingSubmission: pending && typeof pending === 'object' ? { id: String((pending as Record<string, unknown>).id), expectedTransition: (pending as Record<string, unknown>).expectedTransition as TradeV2SubmittedTransition, createdAt: String((pending as Record<string, unknown>).createdAt) } : null, participants: { maker: (participants as Record<string, unknown>).maker as string, taker: (participants as Record<string, unknown>).taker as string }, proposal: proposal && typeof proposal === 'object' ? { assets: (proposal as Record<string, unknown>).assets as ProposalAsset[], expiresAt: String((proposal as Record<string, unknown>).expiresAt), tradeCommitment: String((proposal as Record<string, unknown>).tradeCommitment) } : null }
}
export function parseTradeV2TradeRecord(raw: unknown): TradeV2TradeRecord { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Invalid Trade V2 trade response'); const value = raw as Record<string, unknown>; if (typeof value.tradeId !== 'string' || value.tradeId.length === 0) throw new Error('Invalid Trade V2 trade identifier'); return value as TradeV2TradeRecord }
export class TradeV2Client {
  constructor(private readonly transport: TradeV2Transport) {}
  capabilities() { return discoverTradeV2Capabilities() }
  getCapabilities(auth: TradeV2ApiAuth): Promise<unknown> { return this.transport.request({ path: '/v1/capabilities', method: 'GET', auth }) }
  listTrades(auth: TradeV2ApiAuth, options: { cursor?: string; limit?: number; externalReference?: string } = {}): Promise<unknown> { const query = new URLSearchParams(); if (options.cursor) query.set('cursor', options.cursor); if (options.limit) query.set('limit', String(options.limit)); if (options.externalReference) query.set('externalReference', options.externalReference); return this.transport.request({ path: '/v1/trades' + (query.size ? `?${query}` : ''), method: 'GET', auth }) }
  async getTrade(auth: TradeV2ApiAuth, tradeId: string): Promise<TradeV2TradeRecord> { return parseTradeV2TradeRecord(await this.transport.request({ path: '/v1/trades/' + encodeURIComponent(tradeId), method: 'GET', auth })) }
  getConstructionContext(auth: TradeV2ApiAuth, tradeId: string): Promise<TradeV2ConstructionContext> { return this.transport.request({ path: '/v1/trades/' + encodeURIComponent(tradeId) + '/construction-context', method: 'GET', auth }) as Promise<TradeV2ConstructionContext> }
  private command<T>(auth: TradeV2CommandAuth, path: string, body?: unknown): Promise<T> { return this.transport.request({ path, method: 'POST', auth, body, idempotencyKey: auth.idempotencyKey }) as Promise<T> }
  createTrade(auth: TradeV2CommandAuth, body: { taker: string; assets: readonly ProposalAsset[]; expiresAt: string; externalReference?: string }) { return this.command<{ tradeId: string; proposalId: string; commitment: string }>(auth, '/v1/trades', body) }
  createProposal(auth: TradeV2CommandAuth, tradeId: string, body: { assets: readonly ProposalAsset[]; expiresAt: string }) { return this.command<{ proposalId: string; commitment: string }>(auth, '/v1/trades/' + encodeURIComponent(tradeId) + '/proposals', body) }
  markProposalSeen(auth: TradeV2CommandAuth, tradeId: string, proposalId: string) { return this.command<{ seen: true }>(auth, `/v1/trades/${encodeURIComponent(tradeId)}/proposals/${encodeURIComponent(proposalId)}/seen`) }
  approveProposal(auth: TradeV2CommandAuth, tradeId: string, proposalId: string) { return this.command<{ approved: true; approvals: readonly string[] }>(auth, `/v1/trades/${encodeURIComponent(tradeId)}/proposals/${encodeURIComponent(proposalId)}/approve`) }
  createEscrowIntent(auth: TradeV2CommandAuth, tradeId: string, body: { nonce: string; expectedPda?: string; expiresAt?: string }) { return this.command<{ intentId: string; expectedPda: string | null }>(auth, `/v1/trades/${encodeURIComponent(tradeId)}/escrow-intents`, body) }
  submitInitializationCandidate(auth: TradeV2CommandAuth, intentId: string, body: { signature: string; escrowPda: string; submittedSlot?: string }) { return this.command<{ submissionId: string; verificationStatus: string; expectedTransition: 'authority_initialized' }>(auth, `/v1/escrow-intents/${encodeURIComponent(intentId)}/candidates`, body) }
  submitTransitionCandidate(auth: TradeV2CommandAuth, tradeId: string, body: TradeV2CandidateSubmission) { return this.command<{ submissionId: string; verificationStatus: string; expectedTransition: TradeV2SubmittedTransition }>(auth, `/v1/trades/${encodeURIComponent(tradeId)}/candidates`, body) }
  getTradeHistory(auth: TradeV2ApiAuth, tradeId: string, limit = 50): Promise<unknown> { return this.transport.request({ path: `/v1/trades/${encodeURIComponent(tradeId)}/history?limit=${Math.max(1, Math.min(100, limit))}`, method: 'GET', auth }) }
  listWebhookEndpoints(auth: TradeV2ApiAuth): Promise<unknown> { return this.transport.request({ path: '/v1/webhook-endpoints', method: 'GET', auth }) }
  createWebhookEndpoint(auth: TradeV2CommandAuth, body: { url: string; eventTypes?: readonly string[] }): Promise<unknown> { return this.command(auth, '/v1/webhook-endpoints', body) }
  verifyWebhookEndpoint(auth: TradeV2CommandAuth, endpointId: string, challenge: string): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/verify`, { challenge }) }
  rotateWebhookSecret(auth: TradeV2CommandAuth, endpointId: string, overlapSeconds?: number): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/rotate-secret`, { overlapSeconds }) }
  pauseWebhookEndpoint(auth: TradeV2CommandAuth, endpointId: string): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/pause`) }
  reactivateWebhookEndpoint(auth: TradeV2CommandAuth, endpointId: string): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/reactivate`) }
  retireWebhookEndpoint(auth: TradeV2CommandAuth, endpointId: string): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/retire`) }
  listWebhookDeliveries(auth: TradeV2ApiAuth, endpointId: string, limit = 25): Promise<unknown> { return this.transport.request({ path: `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/deliveries?limit=${Math.max(1, Math.min(100, limit))}`, method: 'GET', auth }) }
  requestWebhookReplay(auth: TradeV2CommandAuth, endpointId: string, from: string, to: string): Promise<unknown> { return this.command(auth, `/v1/webhook-endpoints/${encodeURIComponent(endpointId)}/replays`, { from, to }) }
}
