import { PublicKey } from '@solana/web3.js'
import { TOKEN_2022_PROGRAM_ID, TOKEN_PROGRAM_ID } from '@solana/spl-token'
import { assertTradeAuthorityEntitlementReadiness, tradeAuthorityEntitlementBeneficiary } from './entitlement.js'
import { assertSupportedTradeV2Assets } from './validation.js'
import { TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE, type ProposalAsset, type ProposalSide, type NonSolProposalAsset } from './protocol.js'
export type TradeAuthorityBasketLeg = NonSolProposalAsset
export type TradeAuthorityClaimabilityDecision = { readonly source: 'authenticated_oracle'; readonly side: ProposalSide; readonly index: number; readonly identity: string; readonly oracleSequence: string; readonly observedSlot: string; readonly verdict: 'claimable' | 'unsupported'; readonly evidence: Readonly<Record<string, unknown>>; readonly blockers: readonly string[] }
export type TradeAuthorityRailAccountExplanation = { readonly side: ProposalSide; readonly index: number; readonly kind: TradeAuthorityBasketLeg['kind']; readonly identity: string; readonly accounts: readonly { readonly role: string; readonly address: string }[]; readonly proofFetchedAt?: string; readonly proofContextSlot?: string; readonly ruleSet?: string | null; readonly authorizationDataPresent?: boolean; readonly complete: true }
export type TradeAuthorityBasketAction = 'create' | 'deposit' | 'accept' | 'commit' | 'cancel' | 'recover' | 'release' | 'withdraw' | 'close'
export type TradeAuthorityBasketTerms = { readonly maker: string; readonly taker: string; readonly makerLegs: readonly TradeAuthorityBasketLeg[]; readonly takerLegs: readonly TradeAuthorityBasketLeg[]; readonly makerSolLamports: string; readonly takerSolLamports: string; readonly expiresAt: string; readonly protocolVersion: 1 }
export type TradeAuthorityBasketCommitmentInput = { readonly cluster: string; readonly programId: string; readonly tradeId: string; readonly proposalId: string; readonly maker: string; readonly taker: string; readonly assets: readonly ProposalAsset[]; readonly expiresAt: string }
export type TradeAuthorityBasketPreparation = { readonly action: TradeAuthorityBasketAction; readonly requiredSigner: string | 'permissionless'; readonly executionStrategy: 'trade_session'; readonly orderedLegs: readonly TradeAuthorityBasketLeg[]; readonly beneficiaries: readonly { side: ProposalSide; index: number; wallet: string }[]; readonly railAccounts: readonly TradeAuthorityRailAccountExplanation[]; readonly signs: false; readonly automaticallyRetries: false; readonly rpcDeclaresCompletion: false }
export type TradeAuthorityClaimSlot = TradeAuthorityBasketLeg & { readonly status: 'required' | 'deposited' | 'released' | 'withdrawn' }
export type PreparedTradeAuthorityClaim<T> = { readonly settlementModel: 'atomic_entitlement_durable_delivery'; readonly participant: string; readonly payer: string; readonly requiresCounterpartySignature: false; readonly pendingSlots: readonly TradeAuthorityClaimSlot[]; readonly releaseTransactions: readonly T[] }
export async function prepareClaimRemaining<T>(args: { readonly phase: 'committed'; readonly maker: string; readonly taker: string; readonly participant: string; readonly payer?: string; readonly slots: readonly TradeAuthorityClaimSlot[]; readonly buildReleaseTransaction: (input: { readonly slot: TradeAuthorityClaimSlot; readonly beneficiary: string; readonly payer: string; readonly fetchFreshCnftProof: boolean }) => Promise<T> }): Promise<PreparedTradeAuthorityClaim<T>> {
  if (args.participant !== args.maker && args.participant !== args.taker) throw new Error('Manual claim is available only to a session participant'); const payer = args.payer ?? args.participant; const participants = { maker: args.maker, taker: args.taker }; const pendingSlots = args.slots.filter((slot) => slot.status === 'deposited' && tradeAuthorityEntitlementBeneficiary(slot.side, participants) === args.participant); const releaseTransactions = [] as T[]; for (const slot of pendingSlots) releaseTransactions.push(await args.buildReleaseTransaction({ slot, beneficiary: tradeAuthorityEntitlementBeneficiary(slot.side, participants), payer, fetchFreshCnftProof: slot.kind === 'compressed_nft' })); return { settlementModel: 'atomic_entitlement_durable_delivery', participant: args.participant, payer, requiresCounterpartySignature: false, pendingSlots, releaseTransactions }
}
const encoder = new TextEncoder(); const domain = encoder.encode('SWAPFUN_TRADE_AUTHORITY_V2\0')
function canonical(value: unknown): string { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(',')}}` }
function concat(parts: readonly Uint8Array[]): Uint8Array { const out = new Uint8Array(parts.reduce((total,part) => total + part.length,0)); let offset=0; for (const part of parts) { out.set(part,offset); offset += part.length } return out }
function uuidBytes(value: string): Uint8Array { const compact = value.replaceAll('-',''); if (!/^[0-9a-f]{32}$/i.test(compact)) throw new Error('Invalid UUID'); return Uint8Array.from({ length:16 },(_,index) => Number.parseInt(compact.slice(index*2,index*2+2),16)) }
async function sha256(value: Uint8Array): Promise<Uint8Array> { return new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(value).buffer)) }
function hex(value: Uint8Array): string { return Array.from(value,(byte) => byte.toString(16).padStart(2,'0')).join('') }
export function validateTradeAuthorityBasket(input: Pick<TradeAuthorityBasketCommitmentInput,'maker'|'taker'|'assets'|'expiresAt'>): TradeAuthorityBasketTerms {
  if (input.maker === input.taker) throw new Error('Maker and taker must differ'); new PublicKey(input.maker); new PublicKey(input.taker); assertSupportedTradeV2Assets(input.assets); const sorted = [...input.assets].sort((a,b) => (a.side === b.side ? a.index-b.index : a.side === 'maker' ? -1 : 1)); const makerLegs = sorted.filter((asset): asset is TradeAuthorityBasketLeg => asset.side === 'maker' && asset.kind !== 'sol'); const takerLegs = sorted.filter((asset): asset is TradeAuthorityBasketLeg => asset.side === 'taker' && asset.kind !== 'sol'); if (makerLegs.length > TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE || takerLegs.length > TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE) throw new Error('Trade Authority basket cap exceeded'); const makerSolLamports = sorted.find((asset) => asset.side === 'maker' && asset.kind === 'sol'); const takerSolLamports = sorted.find((asset) => asset.side === 'taker' && asset.kind === 'sol'); if (makerLegs.length === 0 && !makerSolLamports) throw new Error('Maker side is empty'); if (takerLegs.length === 0 && !takerSolLamports) throw new Error('Taker side is empty'); if ([...makerLegs,...takerLegs].some((leg) => (leg.kind === 'spl' || leg.kind === 'token2022') && leg.amount !== '1')) throw new Error('Trade Authority session basket legs must each transfer exactly one token (TRADE_AUTHORITY_SESSION_LEGS_REQUIRE_UNIT_AMOUNT)'); if (!Number.isFinite(Date.parse(input.expiresAt))) throw new Error('Invalid expiry'); return { maker: input.maker, taker: input.taker, makerLegs, takerLegs, makerSolLamports: makerSolLamports?.kind === 'sol' ? makerSolLamports.lamports : '0', takerSolLamports: takerSolLamports?.kind === 'sol' ? takerSolLamports.lamports : '0', expiresAt: input.expiresAt, protocolVersion: 1 }
}
export async function computeTradeAuthorityBasketCommitment(input: TradeAuthorityBasketCommitmentInput): Promise<{ readonly tradeCommitment: string; readonly termsHash: string; readonly canonicalTerms: string }> { const terms = validateTradeAuthorityBasket(input); const canonicalTerms = canonical({ maker:terms.maker,taker:terms.taker,assets:[...terms.makerLegs,...terms.takerLegs],makerSolLamports:terms.makerSolLamports,takerSolLamports:terms.takerSolLamports,expiresAt:terms.expiresAt,protocolVersion:terms.protocolVersion }); const termsHash = await sha256(encoder.encode(canonicalTerms)); const preimage = concat([domain,new Uint8Array([1]),encoder.encode(input.cluster),new Uint8Array([0]),new PublicKey(input.programId).toBytes(),uuidBytes(input.tradeId),uuidBytes(input.proposalId),termsHash]); return { tradeCommitment:`sha256:${hex(await sha256(preimage))}`, termsHash:`sha256:${hex(termsHash)}`, canonicalTerms } }
function legIdentity(leg: TradeAuthorityBasketLeg): string { if (leg.kind === 'compressed_nft') return `${leg.assetId}:${leg.tree}:${leg.leafIndex}`; if (leg.kind === 'core') return leg.assetId; return leg.mint }
export function prepareTradeAuthorityBasketAction(args: { readonly terms: TradeAuthorityBasketTerms; readonly action: TradeAuthorityBasketAction; readonly actor: string; readonly authoritativeRequiredSigner?: string; readonly railAccounts?: readonly TradeAuthorityRailAccountExplanation[]; readonly legStates?: readonly { readonly side: ProposalSide; readonly index: number; readonly status: string }[]; readonly authoritativeObservation?: { readonly oracleSequence: string; readonly observedSlot: string; readonly claimabilityDecisions: readonly TradeAuthorityClaimabilityDecision[] } }): TradeAuthorityBasketPreparation {
  const permissionless = args.action === 'release' || args.action === 'withdraw' || args.action === 'close'; const requiredSigner = permissionless ? 'permissionless' : (args.authoritativeRequiredSigner ?? (args.action === 'accept' || args.action === 'commit' ? args.terms.taker : args.terms.maker)); if (!permissionless && args.actor !== requiredSigner) throw new Error('Wrong signer for Trade Authority basket action'); const orderedLegs=[...args.terms.makerLegs,...args.terms.takerLegs]; const supplied=new Map((args.railAccounts ?? []).map((item)=>[`${item.side}:${item.index}`,item])); const railAccounts=orderedLegs.map((leg)=>{ const key=`${leg.side}:${leg.index}`; const provided=supplied.get(key); if (provided) { if (!provided.complete || provided.kind !== leg.kind || provided.identity !== legIdentity(leg) || provided.accounts.length===0) throw new Error(`Unexplained or substituted rail accounts for ${key}`); if (leg.kind==='compressed_nft') { const age=Date.now()-Date.parse(provided.proofFetchedAt ?? ''); if (!provided.proofContextSlot || !Number.isFinite(age) || age<0 || age>30_000) throw new Error(`Fresh cNFT proof required for ${key}`) } if (leg.kind==='pnft' && provided.ruleSet && provided.authorizationDataPresent !== true) throw new Error(`pNFT authorization data required for ${key}`); return provided } if (leg.kind !== 'spl' && leg.kind !== 'token2022') throw new Error(`Rail-specific accounts are required for ${key}`); return { side:leg.side,index:leg.index,kind:leg.kind,identity:legIdentity(leg),complete:true,accounts:[{ role:'mint',address:leg.mint },{ role:'token_program',address:(leg.kind==='token2022'?TOKEN_2022_PROGRAM_ID:TOKEN_PROGRAM_ID).toBase58() }] } as const })
  if (args.action==='commit') { if (!args.authoritativeObservation) throw new Error('Authoritative Oracle observation is required before commit'); const states=new Map((args.legStates ?? []).map((item)=>[`${item.side}:${item.index}`,item.status])); assertTradeAuthorityEntitlementReadiness({ phase:'taker_funding',participants:{ maker:args.terms.maker,taker:args.terms.taker },oracleSequence:args.authoritativeObservation.oracleSequence,observedSlot:args.authoritativeObservation.observedSlot,slots:orderedLegs.map((leg)=>({ ...leg,status:states.get(`${leg.side}:${leg.index}`)==='deposited'?'deposited' as const:'required' as const,beneficiary:tradeAuthorityEntitlementBeneficiary(leg.side,args.terms),claimabilityDecision:args.authoritativeObservation!.claimabilityDecisions.find((item)=>item.side===leg.side&&item.index===leg.index) as never })) }) }
  return { action:args.action,requiredSigner,executionStrategy:'trade_session',orderedLegs,beneficiaries:orderedLegs.map((leg)=>({ side:leg.side,index:leg.index,wallet:args.action==='release'?tradeAuthorityEntitlementBeneficiary(leg.side,args.terms):(leg.side==='maker'?args.terms.maker:args.terms.taker) })),railAccounts,signs:false,automaticallyRetries:false,rpcDeclaresCompletion:false }
}
