import type { ProposalSide, TradeV2Rail } from './protocol.js'
export type TradeAuthorityEntitlementParticipants = { readonly maker: string; readonly taker: string }
export function tradeAuthorityEntitlementBeneficiary(side: ProposalSide, participants: TradeAuthorityEntitlementParticipants): string { return side === 'maker' ? participants.taker : participants.maker }
export type TradeAuthorityClaimabilityEvidence =
  | { readonly kind: 'spl'; readonly mint: string; readonly freezeAuthority: string | null; readonly custodyDelegate: string | null }
  | { readonly kind: 'token2022'; readonly mint: string; readonly freezeAuthority: string | null; readonly extensionFree: boolean; readonly custodyDelegate: string | null }
  | { readonly kind: 'pnft'; readonly mint: string; readonly metadataImmutable: boolean; readonly ruleSet: string | null; readonly externalDelegate: boolean; readonly tokenRecordUnlocked: boolean }
  | { readonly kind: 'core'; readonly assetId: string; readonly externalFreezeAuthority: string | null; readonly blockingPlugins: readonly string[]; readonly transferable: boolean; readonly updateAuthorityCanAddBlockingPlugin: boolean }
  | { readonly kind: 'compressed_nft'; readonly assetId: string; readonly tree: string; readonly leafIndex: number; readonly proofRefreshSupported: boolean; readonly externalLeafDelegate: string | null }
  | { readonly kind: 'sol'; readonly commitTransferSupported: boolean }
type ClaimabilityLeg = { readonly side: ProposalSide; readonly index: number; readonly kind: TradeV2Rail; readonly mint?: string | null; readonly assetId?: string | null; readonly tree?: string | null; readonly leafIndex?: number | null }
type EntitlementClaimabilityDecision = { readonly source: 'authenticated_oracle'; readonly side: ProposalSide; readonly index: number; readonly identity: string; readonly oracleSequence: string; readonly observedSlot: string; readonly verdict: 'claimable' | 'unsupported'; readonly evidence: TradeAuthorityClaimabilityEvidence; readonly blockers: readonly string[] }
export function tradeAuthorityClaimabilityIdentity(leg: ClaimabilityLeg): string { if (leg.kind === 'compressed_nft') return `${leg.assetId}:${leg.tree}:${leg.leafIndex}`; if (leg.kind === 'core') return String(leg.assetId); if (leg.kind === 'sol') return `sol:${leg.side}`; return String(leg.mint) }
export function tradeAuthorityClaimabilityBlockers(leg: ClaimabilityLeg, evidence: TradeAuthorityClaimabilityEvidence | undefined): readonly string[] {
  const at = `${leg.side}:${leg.index}`; if (!evidence || evidence.kind !== leg.kind) return [`CLAIMABILITY_EVIDENCE_REQUIRED:${at}`]
  if ((leg.kind === 'spl' || leg.kind === 'token2022' || leg.kind === 'pnft') && evidence.kind === leg.kind && evidence.mint !== leg.mint) return [`CLAIMABILITY_IDENTITY_MISMATCH:${at}`]
  if (leg.kind === 'spl' && evidence.kind === 'spl') return evidence.freezeAuthority !== null || evidence.custodyDelegate !== null ? [`SPL_MUTABLE_TRANSFER_AUTHORITY_UNSUPPORTED:${at}`] : []
  if (leg.kind === 'token2022' && evidence.kind === 'token2022') { const blockers: string[] = []; if (evidence.freezeAuthority !== null) blockers.push(`TOKEN_2022_FREEZE_AUTHORITY_UNSUPPORTED:${at}`); if (evidence.extensionFree !== true) blockers.push(`TOKEN_2022_EXTENSIONS_UNSUPPORTED:${at}`); if (evidence.custodyDelegate !== null) blockers.push(`TOKEN_2022_CUSTODY_DELEGATE_UNSUPPORTED:${at}`); return blockers }
  if (leg.kind === 'pnft' && evidence.kind === 'pnft') { const blockers: string[] = []; if (evidence.metadataImmutable !== true) blockers.push(`PNFT_MUTABLE_METADATA_UNSUPPORTED:${at}`); if (evidence.ruleSet !== null) blockers.push(`PNFT_RULE_SET_UNSUPPORTED:${at}`); if (evidence.externalDelegate !== false) blockers.push(`PNFT_EXTERNAL_DELEGATE_UNSUPPORTED:${at}`); if (evidence.tokenRecordUnlocked !== true) blockers.push(`PNFT_LOCKED_TOKEN_RECORD_UNSUPPORTED:${at}`); return blockers }
  if (leg.kind === 'core' && evidence.kind === 'core') { if (evidence.assetId !== leg.assetId) return [`CLAIMABILITY_IDENTITY_MISMATCH:${at}`]; const blockers: string[] = []; if (evidence.externalFreezeAuthority !== null) blockers.push(`CORE_EXTERNAL_FREEZE_AUTHORITY_UNSUPPORTED:${at}`); if (evidence.blockingPlugins.length > 0) blockers.push(`CORE_BLOCKING_PLUGIN_UNSUPPORTED:${at}`); if (evidence.transferable !== true) blockers.push(`CORE_NONTRANSFERABLE_UNSUPPORTED:${at}`); if (evidence.updateAuthorityCanAddBlockingPlugin !== false) blockers.push(`CORE_MUTABLE_TRANSFER_CONTROL_UNSUPPORTED:${at}`); return blockers }
  if (leg.kind === 'compressed_nft' && evidence.kind === 'compressed_nft') { if (evidence.assetId !== leg.assetId || evidence.tree !== leg.tree || evidence.leafIndex !== leg.leafIndex) return [`CLAIMABILITY_IDENTITY_MISMATCH:${at}`]; const blockers: string[] = []; if (evidence.proofRefreshSupported !== true) blockers.push(`CNFT_PROOF_REFRESH_REQUIRED:${at}`); if (evidence.externalLeafDelegate !== null) blockers.push(`CNFT_EXTERNAL_LEAF_DELEGATE_UNSUPPORTED:${at}`); return blockers }
  if (leg.kind === 'sol' && evidence.kind === 'sol') return evidence.commitTransferSupported === true ? [] : [`SOL_COMMIT_TRANSFER_UNSUPPORTED:${at}`]
  return [`CLAIMABILITY_EVIDENCE_REQUIRED:${at}`]
}
export function verifyTradeAuthorityClaimabilityDecision(args: { readonly leg: ClaimabilityLeg; readonly decision: EntitlementClaimabilityDecision | undefined; readonly expectedOracleSequence: string; readonly expectedObservedSlot: string }): readonly string[] {
  const at = `${args.leg.side}:${args.leg.index}`; const decision = args.decision; if (!decision || decision.source !== 'authenticated_oracle') return [`AUTHORITATIVE_CLAIMABILITY_REQUIRED:${at}`]; const blockers: string[] = []
  if (decision.side !== args.leg.side || decision.index !== args.leg.index || decision.identity !== tradeAuthorityClaimabilityIdentity(args.leg)) blockers.push(`CLAIMABILITY_DECISION_IDENTITY_MISMATCH:${at}`)
  if (decision.oracleSequence !== args.expectedOracleSequence || decision.observedSlot !== args.expectedObservedSlot) blockers.push(`CLAIMABILITY_DECISION_STALE:${at}`)
  const derived = tradeAuthorityClaimabilityBlockers(args.leg, decision.evidence); if (decision.verdict !== (derived.length === 0 ? 'claimable' : 'unsupported') || decision.blockers.length !== derived.length || decision.blockers.some((item,index) => item !== derived[index])) blockers.push(`CLAIMABILITY_DECISION_FORGED:${at}`); if (decision.verdict !== 'claimable') blockers.push(...derived); return blockers
}
export function assertTradeAuthorityEntitlementReadiness(args: { readonly phase: 'taker_funding'; readonly participants: TradeAuthorityEntitlementParticipants; readonly oracleSequence: string; readonly observedSlot: string; readonly slots: readonly (ClaimabilityLeg & { readonly status: 'deposited' | 'required'; readonly beneficiary: string; readonly claimabilityDecision?: EntitlementClaimabilityDecision })[] }): void {
  const blockers: string[] = []; if (!/^\d+$/.test(args.oracleSequence) || !/^\d+$/.test(args.observedSlot)) blockers.push('CLAIMABILITY_ORACLE_BINDING_INVALID')
  for (const slot of args.slots) { if (slot.status !== 'deposited') blockers.push(`SLOT_NOT_FUNDED:${slot.side}:${slot.index}`); const beneficiary = tradeAuthorityEntitlementBeneficiary(slot.side,args.participants); if (slot.beneficiary !== beneficiary) blockers.push(`ENTITLEMENT_BENEFICIARY_MISMATCH:${slot.side}:${slot.index}`); blockers.push(...verifyTradeAuthorityClaimabilityDecision({ leg: slot, decision: slot.claimabilityDecision, expectedOracleSequence: args.oracleSequence, expectedObservedSlot: args.observedSlot })) }
  if (blockers.length > 0) throw new Error(`ENTITLEMENT_READINESS_FAILED:${blockers.join(',')}`)
}
