import { ExtensionType, TOKEN_2022_PROGRAM_ID, TOKEN_PROGRAM_ID, getAccount, getExtensionTypes, getMint } from '@solana/spl-token'
import { PublicKey, type Commitment, type Connection } from '@solana/web3.js'
import type { ProposalAsset, SplProposalAsset, Token2022ProposalAsset } from './protocol.js'
import { TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE } from './protocol.js'
type TradeV2StandardTokenAsset = SplProposalAsset | Token2022ProposalAsset
export function assertSupportedTradeV2Assets(assets: readonly ProposalAsset[]): void {
  const counts = { maker: 0, taker: 0 }; const indexes = { maker: new Set<number>(), taker: new Set<number>() }; const identities = new Set<string>(); const solSides = new Set<string>()
  for (const asset of assets) { if (asset.kind === 'sol') { if (asset.index !== 0 || BigInt(asset.lamports) <= 0n || solSides.has(asset.side)) throw new Error('Invalid or duplicate SOL leg'); solSides.add(asset.side); continue } if (!Number.isInteger(asset.index) || asset.index < 0 || asset.index >= TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE) throw new Error('Invalid Trade Authority basket leg index'); if (indexes[asset.side].has(asset.index)) throw new Error('Duplicate Trade Authority basket leg index'); indexes[asset.side].add(asset.index); counts[asset.side] += 1; if (counts[asset.side] > TRADE_AUTHORITY_MAX_NON_SOL_ASSETS_PER_SIDE) throw new Error('Trade Authority basket exceeds the 8-per-side launch cap'); const identity = asset.kind === 'compressed_nft' ? `${asset.kind}:${asset.assetId}:${asset.tree}:${asset.leafIndex}` : asset.kind === 'core' ? `${asset.kind}:${asset.assetId}` : `${asset.kind}:${asset.mint}`; if (identities.has(identity)) throw new Error('Duplicate Trade Authority basket asset'); identities.add(identity); if (asset.kind === 'spl' || asset.kind === 'token2022') { if (BigInt(asset.amount) <= 0n) throw new Error('Trade Authority basket amounts must be positive') } else if (asset.kind === 'compressed_nft' && (!Number.isInteger(asset.leafIndex) || asset.leafIndex < 0)) throw new Error('Invalid compressed NFT leaf index') }
  for (const side of ['maker','taker'] as const) for (let index = 0; index < counts[side]; index += 1) if (!indexes[side].has(index)) throw new Error('Trade Authority basket indexes must be contiguous and ordered')
}
export async function validateClassicSplMint(connection: Connection, mintAddress: string, commitment: Commitment = 'confirmed'): Promise<void> { await getMint(connection, new PublicKey(mintAddress), commitment, TOKEN_PROGRAM_ID) }
export async function validateExtensionFreeToken2022Mint(connection: Connection, mintAddress: string, commitment: Commitment = 'confirmed'): Promise<void> { const mint = await getMint(connection, new PublicKey(mintAddress), commitment, TOKEN_2022_PROGRAM_ID); if (getExtensionTypes(mint.tlvData).length !== 0) throw new Error('Token-2022 mint extensions are not supported') }
export async function findTradeV2SourceTokenAccount(args: { readonly connection: Connection; readonly owner: string; readonly asset: TradeV2StandardTokenAsset; readonly commitment: Commitment }): Promise<string> { const owner = new PublicKey(args.owner); const mint = new PublicKey(args.asset.mint); const program = args.asset.kind === 'token2022' ? TOKEN_2022_PROGRAM_ID : TOKEN_PROGRAM_ID; if (args.asset.kind === 'token2022') await validateExtensionFreeToken2022Mint(args.connection,args.asset.mint,args.commitment); const accounts = await args.connection.getParsedTokenAccountsByOwner(owner,{ programId: program },args.commitment); const required = BigInt(args.asset.amount); const eligible = accounts.value.flatMap(({ pubkey, account }) => { const parsed = account.data && 'parsed' in account.data ? account.data.parsed as { info?: { mint?: unknown; owner?: unknown; delegate?: unknown; state?: unknown; tokenAmount?: { amount?: unknown } } } : null; const info = parsed?.info; if (!info || info.mint !== args.asset.mint || info.owner !== args.owner || info.delegate) return []; const amount = typeof info.tokenAmount?.amount === 'string' ? BigInt(info.tokenAmount.amount) : 0n; if (amount < required || String(info.state ?? '').toLowerCase() === 'frozen') return []; return [pubkey.toBase58()] }); if (args.asset.kind === 'spl') { if (!eligible[0]) throw new Error('No spendable SPL account has the required balance'); return eligible[0] } for (const candidate of eligible) { const account = await getAccount(args.connection,new PublicKey(candidate),args.commitment,program); const extensions = getExtensionTypes(account.tlvData); if (account.owner.equals(owner) && account.mint.equals(mint) && account.amount >= required && account.delegate === null && account.isInitialized && !account.isFrozen && extensions.every((extension) => extension === ExtensionType.ImmutableOwner)) return candidate } throw new Error('No spendable extension-free Token-2022 account has the required balance') }
