export const TRADE_V2_WEBHOOK_SIGNATURE_VERSION = 'v1'
export const TRADE_V2_WEBHOOK_ACCEPTANCE_WINDOW_SECONDS = 300
export const TRADE_V2_WEBHOOK_EVENT_TYPES = ['trade.created','proposal.approved','trade.initialization_verified','trade.acceptance_verified','trade.maker_funding_verified','trade.taker_funding_verified','trade.ready_for_settlement','trade.settlement_submitted','trade.settlement_verified','trade.cancellation_initiated','trade.recovery_initiated','trade.withdrawal_verified','trade.terminal_completion_verified','trade.conflict_detected','trade.oracle_verification_delayed'] as const
export type TradeV2WebhookEventType = typeof TRADE_V2_WEBHOOK_EVENT_TYPES[number]
export type TradeV2WebhookEvent = { readonly schemaVersion: string; readonly eventId: string; readonly type: TradeV2WebhookEventType; readonly occurredAt: string; readonly tradeId: string; readonly externalReference: string | null; readonly authoritativeStatus: string; readonly priorStatus: string | null; readonly oracle: { readonly sequence: string | null; readonly observedSlot: string | null }; readonly pending: Readonly<Record<string, unknown>> | null; readonly conflict: Readonly<Record<string, unknown>> | null; readonly diagnosticId: string; readonly currentStateUrl: string }
export class TradeV2WebhookReplayGuard { readonly deliveryIds = new Set<string>(); readonly eventIds = new Set<string>(); hasDelivery(deliveryId: string): boolean { return this.deliveryIds.has(deliveryId) } hasEvent(eventId: string): boolean { return this.eventIds.has(eventId) } remember(eventId: string, deliveryId: string): void { this.eventIds.add(eventId); this.deliveryIds.add(deliveryId) } }
function header(headers: Headers | Readonly<Record<string, string>>, name: string): string { if (headers instanceof Headers) return headers.get(name) ?? ''; const entry = Object.entries(headers).find(([key]) => key.toLowerCase() === name.toLowerCase()); return entry?.[1] ?? '' }
function bytes(value: string): ArrayBuffer { return new TextEncoder().encode(value).buffer as ArrayBuffer }
function hex(value: ArrayBuffer): string { return [...new Uint8Array(value)].map((part) => part.toString(16).padStart(2, '0')).join('') }
function timingSafeHexEqual(left: string, right: string): boolean { if (left.length !== right.length || !/^[0-9a-f]+$/i.test(left) || !/^[0-9a-f]+$/i.test(right)) return false; let difference = 0; for (let index = 0; index < left.length; index += 1) difference |= left.charCodeAt(index) ^ right.charCodeAt(index); return difference === 0 }
export async function verifyTradeV2Webhook(input: { readonly payloadBytes: Uint8Array; readonly headers: Headers | Readonly<Record<string, string>>; readonly secrets: readonly string[]; readonly endpointId: string; readonly integrationId: string; readonly now?: Date; readonly acceptanceWindowSeconds?: number; readonly replayGuard?: TradeV2WebhookReplayGuard }): Promise<{ event: TradeV2WebhookEvent; duplicateLogicalEvent: boolean }> {
  const eventId = header(input.headers,'x-prismswap-event-id'); const deliveryId = header(input.headers,'x-prismswap-delivery-id'); const timestamp = header(input.headers,'x-prismswap-timestamp'); const version = header(input.headers,'x-prismswap-signature-version'); const signature = header(input.headers,'x-prismswap-signature'); const endpointId = header(input.headers,'x-prismswap-endpoint-id') || input.endpointId; const integrationId = header(input.headers,'x-prismswap-integration-id') || input.integrationId
  if (!eventId || !deliveryId || !timestamp || version !== TRADE_V2_WEBHOOK_SIGNATURE_VERSION || !signature) throw new Error('Invalid Trade V2 webhook signature headers'); if (endpointId !== input.endpointId || integrationId !== input.integrationId) throw new Error('Trade V2 webhook identity mismatch')
  const occurred = Date.parse(timestamp); const now = (input.now ?? new Date()).getTime(); const windowMs = (input.acceptanceWindowSeconds ?? TRADE_V2_WEBHOOK_ACCEPTANCE_WINDOW_SECONDS) * 1000; if (!Number.isFinite(occurred) || Math.abs(now - occurred) > windowMs) throw new Error('Trade V2 webhook timestamp is outside the acceptance window'); if (input.replayGuard?.hasDelivery(deliveryId)) throw new Error('Trade V2 webhook delivery replay rejected')
  const digest = hex(await crypto.subtle.digest('SHA-256', input.payloadBytes.slice().buffer as ArrayBuffer)); const suppliedDigest = header(input.headers,'x-prismswap-content-sha256'); if (suppliedDigest && !timingSafeHexEqual(digest, suppliedDigest)) throw new Error('Trade V2 webhook payload digest mismatch')
  const signingPayload = [version,eventId,deliveryId,timestamp,endpointId,integrationId,digest].join('.'); let valid = false; for (const secret of input.secrets) { const key = await crypto.subtle.importKey('raw', bytes(secret), { name:'HMAC', hash:'SHA-256' }, false, ['sign']); const expected = hex(await crypto.subtle.sign('HMAC', key, bytes(signingPayload))); valid ||= timingSafeHexEqual(expected, signature) }
  if (!valid) throw new Error('Trade V2 webhook signature is invalid'); const event = parseTradeV2WebhookEvent(JSON.parse(new TextDecoder().decode(input.payloadBytes))); if (event.eventId !== eventId) throw new Error('Trade V2 webhook event identity mismatch'); const duplicateLogicalEvent = input.replayGuard?.hasEvent(eventId) ?? false; input.replayGuard?.remember(eventId, deliveryId); return { event, duplicateLogicalEvent }
}
export function parseTradeV2WebhookEvent(raw: unknown): TradeV2WebhookEvent { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Invalid Trade V2 webhook event'); const value = raw as Record<string, unknown>; if (typeof value.schemaVersion !== 'string' || typeof value.eventId !== 'string' || typeof value.type !== 'string' || !TRADE_V2_WEBHOOK_EVENT_TYPES.includes(value.type as TradeV2WebhookEventType) || typeof value.occurredAt !== 'string' || !Number.isFinite(Date.parse(value.occurredAt)) || typeof value.tradeId !== 'string' || typeof value.authoritativeStatus !== 'string' || typeof value.diagnosticId !== 'string' || typeof value.currentStateUrl !== 'string') throw new Error('Invalid Trade V2 webhook event'); const oracle = value.oracle; if (!oracle || typeof oracle !== 'object') throw new Error('Invalid Trade V2 webhook Oracle state'); return value as TradeV2WebhookEvent }
